import type { Bounty, UserBounty, AppNotification } from "./types";

export const BOUNTIES: Bounty[] = [
  {
    id: "1",
    title: "Design a BountyHive Summer Poster",
    description: "Create an eye-catching summer themed poster for BountyHive. Must include logo and color palette.",
    type: "creative",
    category: "Creative",
    poolAmount: "150",
    poolUsd: "720",
    winnerCount: 3,
    perWinnerAmount: "50",
    winnerSelection: "manual",
    participants: 128,
    timeLeftSeconds: 2 * 3600 + 14 * 60 + 36,
    isHot: true,
    icon: "rocket",
    creatorName: "BountyHive",
  },
  {
    id: "2",
    title: "BountyHive X Post Challenge",
    description: "Post about BountyHive on X (Twitter). Tag @BountyHive and use #BountyHive. Must have at least 5 likes.",
    type: "task",
    category: "Social",
    poolAmount: "75",
    poolUsd: "360",
    winnerCount: 5,
    perWinnerAmount: "15",
    winnerSelection: "draw",
    participants: 86,
    timeLeftSeconds: 1 * 3600 + 9 * 60 + 15,
    isHot: false,
    icon: "x",
    creatorName: "SocialDAO",
  },
  {
    id: "3",
    title: "Analytics Dashboard Ideas",
    description: "Submit your best ideas for improving the BountyHive analytics dashboard. Detailed writeups preferred.",
    type: "task",
    category: "Analytics",
    poolAmount: "100",
    poolUsd: "480",
    winnerCount: 4,
    perWinnerAmount: "25",
    winnerSelection: "manual",
    participants: 64,
    timeLeftSeconds: 3 * 3600 + 22 * 60 + 10,
    isHot: false,
    icon: "chart",
    creatorName: "DataLabs",
  },
  {
    id: "4",
    title: "Build a Bounty Submission Bot",
    description: "Build a Telegram bot that lets users submit bounty proofs directly from Telegram chat.",
    type: "task",
    category: "Dev",
    poolAmount: "200",
    poolUsd: "960",
    winnerCount: 2,
    perWinnerAmount: "100",
    winnerSelection: "manual",
    participants: 112,
    timeLeftSeconds: 5 * 3600 + 18 * 60 + 42,
    isHot: false,
    icon: "code",
    creatorName: "TonBuilders",
  },
  {
    id: "5",
    title: "Best TON Ecosystem Meme",
    description: "Create the funniest, most shareable meme about the TON ecosystem. Winners chosen by community vote.",
    type: "creative",
    category: "Creative",
    poolAmount: "50",
    poolUsd: "240",
    winnerCount: 3,
    perWinnerAmount: "16.67",
    winnerSelection: "draw",
    participants: 203,
    timeLeftSeconds: 0 * 3600 + 45 * 60 + 22,
    isHot: true,
    icon: "star",
    creatorName: "MemeLabs",
  },
  {
    id: "6",
    title: "TON Twitter Growth Sprint",
    description: "Retweet and comment on 5 TON-related posts. Screenshot proof required.",
    type: "task",
    category: "Social",
    poolAmount: "30",
    poolUsd: "144",
    winnerCount: 10,
    perWinnerAmount: "3",
    winnerSelection: "draw",
    participants: 47,
    timeLeftSeconds: 4 * 3600 + 0 * 60 + 0,
    isHot: false,
    icon: "trophy",
    creatorName: "GrowthDAO",
  },
];

export const CATEGORIES = ["All", "Creative", "Social", "Analytics", "Dev"] as const;

export const USER_BOUNTIES: UserBounty[] = [
  {
    id: "1",
    title: "Design a BountyHive Summer Poster",
    poolAmount: "150",
    perWinnerAmount: "50",
    winnerCount: 3,
    participants: 128,
    timeLeftSeconds: 2 * 3600 + 14 * 60 + 36,
    status: "active",
    role: "joined",
    icon: "rocket",
    category: "Creative",
  },
  {
    id: "5",
    title: "Best TON Ecosystem Meme",
    poolAmount: "50",
    perWinnerAmount: "16.67",
    winnerCount: 3,
    participants: 203,
    timeLeftSeconds: 0,
    status: "won",
    role: "joined",
    icon: "star",
    category: "Creative",
  },
  {
    id: "6",
    title: "TON Twitter Growth Sprint",
    poolAmount: "30",
    perWinnerAmount: "3",
    winnerCount: 10,
    participants: 47,
    timeLeftSeconds: 0,
    status: "ended",
    role: "joined",
    icon: "trophy",
    category: "Social",
  },
  {
    id: "2",
    title: "BountyHive X Post Challenge",
    poolAmount: "75",
    perWinnerAmount: "15",
    winnerCount: 5,
    participants: 86,
    timeLeftSeconds: 1 * 3600 + 9 * 60 + 15,
    status: "active",
    role: "created",
    icon: "x",
    category: "Social",
  },
  {
    id: "7",
    title: "Analytics Deep Dive Report",
    poolAmount: "120",
    perWinnerAmount: "60",
    winnerCount: 2,
    participants: 34,
    timeLeftSeconds: 0,
    status: "ended",
    role: "created",
    icon: "chart",
    category: "Analytics",
  },
];

export const NOTIFICATIONS: AppNotification[] = [
  {
    id: "1",
    type: "winner",
    title: "You won a bounty!",
    body: "You were selected as a winner in \"Best TON Ecosystem Meme\". Claim your +16.67 TON reward.",
    timeAgo: "2m ago",
    isToday: true,
    read: false,
  },
  {
    id: "2",
    type: "deadline",
    title: "Deadline approaching",
    body: "\"BountyHive X Post Challenge\" ends in 1h 9m. Make sure your submission is ready.",
    timeAgo: "15m ago",
    isToday: true,
    read: false,
  },
  {
    id: "3",
    type: "submission",
    title: "New submission received",
    body: "Someone submitted proof for your bounty \"BountyHive X Post Challenge\".",
    timeAgo: "1h ago",
    isToday: true,
    read: true,
  },
  {
    id: "4",
    type: "funded",
    title: "Bounty fully funded",
    body: "\"Analytics Deep Dive Report\" received its full 120 TON funding and is now live.",
    timeAgo: "3h ago",
    isToday: false,
    read: true,
  },
  {
    id: "5",
    type: "winner",
    title: "Winners selected",
    body: "Manual winners have been chosen for \"Analytics Deep Dive Report\". 2 winners rewarded.",
    timeAgo: "1d ago",
    isToday: false,
    read: true,
  },
];
